title = "Centralized logging with CDK"
#googleAnalytics = "UA-174210693-1"
languageCode = "ko-KR"
defaultContentLanguage = "ko"
theme = "learn"
showHeaderLanguageChooser=true
defaultContentLanguageInSubdir= true
relativeURLs=true
CanonifyURLs=true
#metaDataFormat = "yaml"
#baseURL = "https://master.dsd6loerysixy.amplifyapp.com/"
baseURL = "http://localhost:1313/"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  showVisitedLinks = false
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "aws"
  disableSearch = false
  disableAssetsBusting = true
  disableLanguageSwitchingButton = false
  disableShortcutsTitle = true
  disableInlineCopyToClipBoard = true
  author = "Dongmin Lee"

[[menu.shortcuts]] 
  name = "<i class='fab fa-aws'></i> AWS Homepage"
  url = "https://aws.amazon.com/"
  weight = 1000

[[menu.shortcuts]]
  name = "<i class='fas fa-blog'></i> AWS Blog"
  url = "https://aws.amazon.com/blogs/aws/"
  weight = 1020

[[menu.shortcuts]]
  name = "<i class='fab fa-github'></i> Github"
  url = "https://github.com/reoim/centralized-logging-skeleton.git"
  weight = 1040

[Languages]
  [Languages.ko]
    weight = 1
    languageName = "한국어"

  [Languages.en]
    weight = 2
    languageName = "English"

[deployment]
  [[deployment.targets]]
    name = "s3"
    URL = "s3://forecast-demogo-web-site?region=ap-northeast-2"
